package cn.edustar.jitar.pojos;

import java.util.Date;

/**
 * ActionUserUnit generated by MyEclipse Persistence Tools
 */

public class ActionUserUnit implements java.io.Serializable {

	private static final long serialVersionUID = -944749976339866268L;
  
	private int actionUserId;
	private int actionId;
	private String title;
	private String trueName;
	private String loginName;
	private String nickName;
	private String unitName;
	private String unitTitle;
	private int userId;	
	private int attendUserCount;
	private String actionUserDescription;
	private Integer inviteUserId;
	private int isApprove;
	private int actionUserStatus;
	private int ownerId;
	private String ownerType;
	private int createUserId;
	private Date createDate;
	private int actionType;
	private String actionDescription;
	private int userLimit;
	private Date startDateTime;
	private Date finishDateTime;
	private Date attendLimitDateTime;
	private Date actionUserCreateDate;	
	private String place;
	private int attendCount;
	private int attendSuccessCount;
	private int attendQuitCount;
	private int attendFailCount;
	private int actionStatus;
	private int visibility;
	private int isLock;
	
	public int getActionUserId() {
		return actionUserId;
	}
	public void setActionUserId(int actionUserId) {
		this.actionUserId = actionUserId;
	}
	public int getActionId() {
		return actionId;
	}
	public void setActionId(int actionId) {
		this.actionId = actionId;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getTrueName() {
		return trueName;
	}
	public void setTrueName(String trueName) {
		this.trueName = trueName;
	}
	public String getLoginName() {
		return loginName;
	}
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}
	public String getNickName() {
		return nickName;
	}
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}
	public String getUnitName() {
		return unitName;
	}
	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}
	public String getUnitTitle() {
		return unitTitle;
	}
	public void setUnitTitle(String unitTitle) {
		this.unitTitle = unitTitle;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public int getAttendUserCount() {
		return attendUserCount;
	}
	public void setAttendUserCount(int attendUserCount) {
		this.attendUserCount = attendUserCount;
	}
	public String getActionUserDescription() {
		return actionUserDescription;
	}
	public void setActionUserDescription(String actionUserDescription) {
		this.actionUserDescription = actionUserDescription;
	}
	public Integer getInviteUserId() {
		return inviteUserId;
	}
	public void setInviteUserId(Integer inviteUserId) {
		this.inviteUserId = inviteUserId;
	}
	public int getIsApprove() {
		return isApprove;
	}
	public void setIsApprove(int isApprove) {
		this.isApprove = isApprove;
	}
	public int getActionUserStatus() {
		return actionUserStatus;
	}
	public void setActionUserStatus(int actionUserStatus) {
		this.actionUserStatus = actionUserStatus;
	}
	
	public int getOwnerId() {
		return ownerId;
	}
	public void setOwnerId(int ownerId) {
		this.ownerId = ownerId;
	}
	public String getOwnerType() {
		return ownerType;
	}
	public void setOwnerType(String ownerType) {
		this.ownerType = ownerType;
	}
	public int getCreateUserId() {
		return createUserId;
	}
	public void setCreateUserId(int createUserId) {
		this.createUserId = createUserId;
	}
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	public int getActionType() {
		return actionType;
	}
	public void setActionType(int actionType) {
		this.actionType = actionType;
	}
	public String getActionDescription() {
		return actionDescription;
	}
	public void setActionDescription(String actionDescription) {
		this.actionDescription = actionDescription;
	}
	public int getUserLimit() {
		return userLimit;
	}
	public void setUserLimit(int userLimit) {
		this.userLimit = userLimit;
	}
	public Date getStartDateTime() {
		return startDateTime;
	}
	public void setStartDateTime(Date startDateTime) {
		this.startDateTime = startDateTime;
	}
	public Date getFinishDateTime() {
		return finishDateTime;
	}
	public void setFinishDateTime(Date finishDateTime) {
		this.finishDateTime = finishDateTime;
	}
	public Date getAttendLimitDateTime() {
		return attendLimitDateTime;
	}
	public void setAttendLimitDateTime(Date attendLimitDateTime) {
		this.attendLimitDateTime = attendLimitDateTime;
	}
	public String getPlace() {
		return place;
	}
	public void setPlace(String place) {
		this.place = place;
	}
	public int getAttendCount() {
		return attendCount;
	}
	public void setAttendCount(int attendCount) {
		this.attendCount = attendCount;
	}
	public int getAttendSuccessCount() {
		return attendSuccessCount;
	}
	public void setAttendSuccessCount(int attendSuccessCount) {
		this.attendSuccessCount = attendSuccessCount;
	}
	public int getAttendQuitCount() {
		return attendQuitCount;
	}
	public void setAttendQuitCount(int attendQuitCount) {
		this.attendQuitCount = attendQuitCount;
	}
	public int getAttendFailCount() {
		return attendFailCount;
	}
	public void setAttendFailCount(int attendFailCount) {
		this.attendFailCount = attendFailCount;
	}
	public int getActionStatus() {
		return actionStatus;
	}
	public void setActionStatus(int actionStatus) {
		this.actionStatus = actionStatus;
	}
	public int getVisibility() {
		return visibility;
	}
	public void setVisibility(int visibility) {
		this.visibility = visibility;
	}
	public int getIsLock() {
		return isLock;
	}
	public void setIsLock(int isLock) {
		this.isLock = isLock;
	}
	public Date getActionUserCreateDate() {
		return actionUserCreateDate;
	}
	public void setActionUserCreateDate(Date actionUserCreateDate) {
		this.actionUserCreateDate = actionUserCreateDate;
	}

}