package cn.edustar.jitar.pojos;
import java.util.*;

/**
 * CPrepareCourse generated by MyEclipse Persistence Tools
 * 
 * 
 */

public class PrepareCourse implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2339210782253880822L;

	/** 备课标识 */
	private Integer prepareCourseId;
	
	/** 备课名称 */
	private String title;
	
	/** 备课发起人标识 */
	private Integer createUserId;
	
	/** 备课主备人标识 */
	private Integer leaderId;
	
	/** 备课创建时间 */
	private Date createDate;
	
	/** 备课开始时间 */
	private Date startDate;
	
	/** 备课结束时间 */
	private Date endDate;
	
	/** 备课描述 */
	private String description;
	
	/** 共案内容 */
	private String commonContent;
	
	/** 备课所属学科 */
	private Integer metaSubjectId;
	
	/** 备课所属学段 */
	private Integer gradeId;
	
	/** 备课标签 */
	private String tags;
	
	/** 成员数 */
	private int memberCount;
	
	/** 文章数 */
	private int articleCount;
	
	/** 资源数 */
	private int resourceCount;
	
	/** 讨论主题回复数数 */
	private int topicReplyCount;
	
	/** 讨论主题数 */
	private int topicCount;
	
	/** 活动数 */
	private int actionCount;
	
	/** 查看数 */
	private int viewCount;
	
	/** 状态 0:正常，1：待审核，2：锁定，其他未知 */
	private int status;
	
	/** 编写共案锁定时间 */
	private Date lockedDate;
	
	/** 当前共案编写人标识 */
	private Integer lockedUserId;
	
	/** 共案所使用的编辑历史标识 */
	private Integer prepareCourseEditId;
	
	/** 备课所属的备课计划 */
	private Integer prepareCoursePlanId;
	
	/** 是否生成了备课 */
	private Boolean prepareCourseGenerated;
	
	/** 显示顺序 */
	private Integer itemOrder;
	
	/** 是否推荐状态： false - 未推荐，true - 推荐 */
	private boolean recommendState;
	
	/** 共案内容类型：0未指定；1在线编辑HTML；2Word编辑，Flash显示 */
	private int contentType = 0;

	/** 全球唯一标识符 */
	private String objectGuid = java.util.UUID.randomUUID().toString().toUpperCase();

	// Constructors

	public String getObjectGuid() {
		return objectGuid;
	}

	public void setObjectGuid(String objectGuid) {
		this.objectGuid = objectGuid;
	}

	public Integer getItemOrder() {
		return itemOrder;
	}

	public void setItemOrder(Integer itemOrder) {
		this.itemOrder = itemOrder;
	}

	/** default constructor */
	public PrepareCourse() {
	}

	// Property accessors

	public Integer getPrepareCourseId() {
		return this.prepareCourseId;
	}

	public void setPrepareCourseId(Integer prepareCourseId) {
		this.prepareCourseId = prepareCourseId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Integer getLeaderId() {
		return this.leaderId;
	}

	public void setLeaderId(Integer leaderId) {
		this.leaderId = leaderId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCommonContent() {
		return this.commonContent;
	}

	public void setCommonContent(String commonContent) {
		this.commonContent = commonContent;
	}

	public Integer getMetaSubjectId() {
		return this.metaSubjectId;
	}

	public void setMetaSubjectId(Integer metaSubjectId) {
		this.metaSubjectId = metaSubjectId;
	}

	public Integer getGradeId() {
		return this.gradeId;
	}

	public void setGradeId(Integer gradeId) {
		this.gradeId = gradeId;
	}

	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	public int getMemberCount() {
		return this.memberCount;
	}

	public void setMemberCount(int memberCount) {
		this.memberCount = memberCount;
	}

	public int getArticleCount() {
		return this.articleCount;
	}

	public void setArticleCount(int articleCount) {
		this.articleCount = articleCount;
	}

	public int getResourceCount() {
		return this.resourceCount;
	}

	public void setResourceCount(int resourceCount) {
		this.resourceCount = resourceCount;
	}

	public int getTopicReplyCount() {
		return this.topicReplyCount;
	}

	public void setTopicReplyCount(int topicReplyCount) {
		this.topicReplyCount = topicReplyCount;
	}

	public int getTopicCount() {
		return this.topicCount;
	}

	public void setTopicCount(int topicCount) {
		this.topicCount = topicCount;
	}

	public int getActionCount() {
		return this.actionCount;
	}

	public void setActionCount(int actionCount) {
		this.actionCount = actionCount;
	}

	public int getViewCount() {
		return this.viewCount;
	}

	public void setViewCount(int viewCount) {
		this.viewCount = viewCount;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getLockedDate() {
		return this.lockedDate;
	}

	public void setLockedDate(Date lockedDate) {
		this.lockedDate = lockedDate;
	}

	public Integer getLockedUserId() {
		return this.lockedUserId;
	}

	public void setLockedUserId(Integer lockedUserId) {
		this.lockedUserId = lockedUserId;
	}

	public Integer getPrepareCourseEditId() {
		return this.prepareCourseEditId;
	}

	public void setPrepareCourseEditId(Integer prepareCourseEditId) {
		this.prepareCourseEditId = prepareCourseEditId;
	}

	public Integer getPrepareCoursePlanId() {
		return prepareCoursePlanId;
	}

	public void setPrepareCoursePlanId(Integer prepareCoursePlanId) {
		this.prepareCoursePlanId = prepareCoursePlanId;
	}

	public Boolean getPrepareCourseGenerated() {
		return prepareCourseGenerated;
	}

	public void setPrepareCourseGenerated(Boolean prepareCourseGenerated) {
		this.prepareCourseGenerated = prepareCourseGenerated;
	}
	/** 是否推荐状态： false - 未推荐，true - 推荐 */
	public boolean getRecommendState() {
		return this.recommendState;
	}

	/** 是否推荐状态： false - 未推荐，true - 推荐 */
	public void setRecommendState(boolean recommendState) {
		this.recommendState = recommendState;
	}

	public int getContentType() {
		return contentType;
	}

	public void setContentType(int contentType) {
		this.contentType = contentType;
	}




}