package cn.edustar.jitar.pojos;

import java.util.Date;

/**
 * CPrepareCourseStage generated by MyEclipse Persistence Tools
 */

public class PrepareCourseStage implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 7778678993573239667L;
	private Integer prepareCourseStageId;
	private Integer prepareCourseId;
	private String title;
	private Date beginDate;
	private Date finishDate;
	private String description;
	private Integer orderIndex;

	// Constructors

	/** default constructor */
	public PrepareCourseStage() {
	}

	/** full constructor */
	public PrepareCourseStage(Integer prepareCourseId, String title,
			Date beginDate, Date finishDate, Integer orderIndex) {
		this.prepareCourseId = prepareCourseId;
		this.title = title;
		this.beginDate = beginDate;
		this.finishDate = finishDate;
		this.orderIndex = orderIndex;
	}

	// Property accessors

	public Integer getPrepareCourseStageId() {
		return this.prepareCourseStageId;
	}

	public void setPrepareCourseStageId(Integer prepareCourseStageId) {
		this.prepareCourseStageId = prepareCourseStageId;
	}

	public Integer getPrepareCourseId() {
		return this.prepareCourseId;
	}

	public void setPrepareCourseId(Integer prepareCourseId) {
		this.prepareCourseId = prepareCourseId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

	public Integer getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}