package cn.edustar.jitar.pojos;

import java.util.Date;

/**
 * CPrepareCourseMember generated by MyEclipse Persistence Tools
 */

public class PrepareCourseMember implements java.io.Serializable {

	// Fields
	/**  */
	private static final long serialVersionUID = -5492652737891323606L;
	private int prepareCourseMemberId;
	private int prepareCourseId;
	private int userId;
	private String privateContent;
	private Integer replyCount;
	private Date joinDate;
	private int status;
	private Date contentLastupdated;
	
	/** 精华状态：false - 普通，true - 精华 */
	private boolean bestState;
	/** contentType:0:未设置，编写个案之前必须进行下选择，1：直接编辑内容，2:doc文档, 3:docx文档  4:直接上传doc docx文件*/
	private int contentType = 0;
	
	public Date getContentLastupdated() {
		return contentLastupdated;
	}

	public void setContentLastupdated(Date contentLastupdated) {
		if (null == contentLastupdated) {
			contentLastupdated = new Date();
		}
		this.contentLastupdated = contentLastupdated;
	}

	/** 精华状态：false - 普通，true - 精华 */
	public boolean getBestState() {
		return this.bestState;
	}

	/** 精华状态：false - 普通，true - 精华 */
	public void setBestState(boolean bestState) {
		this.bestState = bestState;
	}

	public int getPrepareCourseMemberId() {
		return prepareCourseMemberId;
	}

	public void setPrepareCourseMemberId(int prepareCourseMemberId) {
		this.prepareCourseMemberId = prepareCourseMemberId;
	}

	public int getPrepareCourseId() {
		return prepareCourseId;
	}

	public void setPrepareCourseId(int prepareCourseId) {
		this.prepareCourseId = prepareCourseId;
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getPrivateContent() {
		return privateContent;
	}

	public void setPrivateContent(String privateContent) {
		this.privateContent = privateContent;
	}

	public Integer getReplyCount() {
		return replyCount;
	}

	public void setReplyCount(Integer replyCount) {
		this.replyCount = replyCount;
	}

	public Date getJoinDate() {
		return joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getContentType() {
		return contentType;
	}

	public void setContentType(int contentType) {
		this.contentType = contentType;
	}
}