package cn.edustar.jitar.pojos;

import java.util.Date;

/**
 * CPrepareCourseTopicReply generated by MyEclipse Persistence Tools
 */

public class PrepareCourseTopicReply implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 8221135159709098696L;
	private Integer prepareCourseTopicReplyId;
	private Integer prepareCourseStageId;
	private Integer prepareCourseTopicId;
	private Integer prepareCourseId;
	private String title;
	private Date createDate;
	private Integer userId;
	private String content;

	// Constructors

	/** default constructor */
	public PrepareCourseTopicReply() {
	}

	/** minimal constructor */
	public PrepareCourseTopicReply(Integer prepareCourseStageId,
			Integer prepareCourseTopicId, Integer prepareCourseId,
			Date createDate, Integer userId) {
		this.prepareCourseStageId = prepareCourseStageId;
		this.prepareCourseTopicId = prepareCourseTopicId;
		this.prepareCourseId = prepareCourseId;
		this.createDate = createDate;
		this.userId = userId;
	}

	/** full constructor */
	public PrepareCourseTopicReply(Integer prepareCourseStageId,
			Integer prepareCourseTopicId, Integer prepareCourseId, String title,
			Date createDate, Integer userId, String content) {
		this.prepareCourseStageId = prepareCourseStageId;
		this.prepareCourseTopicId = prepareCourseTopicId;
		this.prepareCourseId = prepareCourseId;
		this.title = title;
		this.createDate = createDate;
		this.userId = userId;
		this.content = content;
	}

	// Property accessors

	public Integer getPrepareCourseTopicReplyId() {
		return this.prepareCourseTopicReplyId;
	}

	public void setPrepareCourseTopicReplyId(Integer prepareCourseTopicReplyId) {
		this.prepareCourseTopicReplyId = prepareCourseTopicReplyId;
	}

	public Integer getPrepareCourseStageId() {
		return this.prepareCourseStageId;
	}

	public void setPrepareCourseStageId(Integer prepareCourseStageId) {
		this.prepareCourseStageId = prepareCourseStageId;
	}

	public Integer getPrepareCourseTopicId() {
		return this.prepareCourseTopicId;
	}

	public void setPrepareCourseTopicId(Integer prepareCourseTopicId) {
		this.prepareCourseTopicId = prepareCourseTopicId;
	}

	public Integer getPrepareCourseId() {
		return this.prepareCourseId;
	}

	public void setPrepareCourseId(Integer prepareCourseId) {
		this.prepareCourseId = prepareCourseId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}