package cn.edustar.jitar.pojos;

import java.util.Date;

/**
 * CPrepareCourseEdit generated by MyEclipse Persistence Tools
 */

public class PrepareCourseEdit implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 8876903204488607173L;
	private Integer prepareCourseEditId;
	private Integer prepareCourseId;
	private Date editDate;
	private Integer editUserId;
	private String content;
	private Integer lockStatus;

	// Constructors

	/** default constructor */
	public PrepareCourseEdit() {
	}

	// Property accessors

	public Integer getPrepareCourseEditId() {
		return this.prepareCourseEditId;
	}

	public void setPrepareCourseEditId(Integer prepareCourseEditId) {
		this.prepareCourseEditId = prepareCourseEditId;
	}

	public Integer getPrepareCourseId() {
		return this.prepareCourseId;
	}

	public void setPrepareCourseId(Integer prepareCourseId) {
		this.prepareCourseId = prepareCourseId;
	}

	public Date getEditDate() {
		return this.editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	public Integer getEditUserId() {
		return this.editUserId;
	}

	public void setEditUserId(Integer editUserId) {
		this.editUserId = editUserId;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getLockStatus() {
		return this.lockStatus;
	}

	public void setLockStatus(Integer lockStatus) {
		this.lockStatus = lockStatus;
	}

}