package cn.edustar.jitar.pojos;

import java.util.Date;

/**
 * CPrepareCourseResource generated by MyEclipse Persistence Tools
 */

public class PrepareCourseResource implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -4783561220561733897L;
	private Integer prepareCourseResourceId;
	private Integer resourceId;
	private Integer prepareCourseStageId;
	private Integer prepareCourseId;
	private Integer userId;
	private Date createDate;
	private String resourceTitle;

	// Constructors

	/** default constructor */
	public PrepareCourseResource() {
	}

	/** full constructor */
	public PrepareCourseResource(Integer resourceId,
			Integer prepareCourseStageId, Integer prepareCourseId, Integer userId,
			Date createDate, String resourceTitle) {
		this.resourceId = resourceId;
		this.prepareCourseStageId = prepareCourseStageId;
		this.prepareCourseId = prepareCourseId;
		this.userId = userId;
		this.createDate = createDate;
		this.resourceTitle = resourceTitle;
	}

	// Property accessors

	public Integer getPrepareCourseResourceId() {
		return this.prepareCourseResourceId;
	}

	public void setPrepareCourseResourceId(Integer prepareCourseResourceId) {
		this.prepareCourseResourceId = prepareCourseResourceId;
	}

	public Integer getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}

	public Integer getPrepareCourseStageId() {
		return this.prepareCourseStageId;
	}

	public void setPrepareCourseStageId(Integer prepareCourseStageId) {
		this.prepareCourseStageId = prepareCourseStageId;
	}

	public Integer getPrepareCourseId() {
		return this.prepareCourseId;
	}

	public void setPrepareCourseId(Integer prepareCourseId) {
		this.prepareCourseId = prepareCourseId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getResourceTitle() {
		return this.resourceTitle;
	}

	public void setResourceTitle(String resourceTitle) {
		this.resourceTitle = resourceTitle;
	}

}