package cn.edustar.jitar.pojos;

import java.util.Date;

/**
 * CPrepareCourseVideo generated by MyEclipse Persistence Tools
 */

public class PrepareCourseVideo implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -4783561220561733897L;
	private Integer prepareCourseVideoId;
	private Integer videoId;
	private Integer prepareCourseId;
	private Integer userId;
	private Date createDate;
	private String videoTitle;

	// Constructors

	/** default constructor */
	public PrepareCourseVideo() {
	}

	/** full constructor */
	public PrepareCourseVideo(Integer videoId,
			Integer prepareCourseId, Integer userId,
			Date createDate, String videoTitle) {
		this.videoId = videoId;
		this.prepareCourseId = prepareCourseId;
		this.userId = userId;
		this.createDate = createDate;
		this.videoTitle = videoTitle;
	}

	// Property accessors

	public Integer getPrepareCourseVideoId() {
		return this.prepareCourseVideoId;
	}

	public void setPrepareCourseVideoId(Integer prepareCourseVideoId) {
		this.prepareCourseVideoId = prepareCourseVideoId;
	}

	public Integer getVideoId() {
		return this.videoId;
	}

	public void setVideoId(Integer videoId) {
		this.videoId = videoId;
	}


	public Integer getPrepareCourseId() {
		return this.prepareCourseId;
	}

	public void setPrepareCourseId(Integer prepareCourseId) {
		this.prepareCourseId = prepareCourseId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getVideoTitle() {
		return this.videoTitle;
	}

	public void setVideoTitle(String videoTitle) {
		this.videoTitle = videoTitle;
	}

}