package cn.edustar.jitar.pojos;

import java.util.Date;

/**
 * CPrepareCourseTopic generated by MyEclipse Persistence Tools
 */

public class PrepareCourseTopic implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -2452118760713165276L;
	private Integer prepareCourseTopicId;
	private Integer prepareCourseId;
	private Integer prepareCourseStageId;
	private Date createDate;
	private String title;
	private Integer userId;
	private String content;

	// Constructors

	/** default constructor */
	public PrepareCourseTopic() {
	}

	/** full constructor */
	public PrepareCourseTopic(Integer prepareCourseId,
			Integer prepareCourseStageId, Date createDate, String title,
			Integer userId, String content) {
		this.prepareCourseId = prepareCourseId;
		this.prepareCourseStageId = prepareCourseStageId;
		this.createDate = createDate;
		this.title = title;
		this.userId = userId;
		this.content = content;
	}

	// Property accessors

	public Integer getPrepareCourseTopicId() {
		return this.prepareCourseTopicId;
	}

	public void setPrepareCourseTopicId(Integer prepareCourseTopicId) {
		this.prepareCourseTopicId = prepareCourseTopicId;
	}

	public Integer getPrepareCourseId() {
		return this.prepareCourseId;
	}

	public void setPrepareCourseId(Integer prepareCourseId) {
		this.prepareCourseId = prepareCourseId;
	}

	public Integer getPrepareCourseStageId() {
		return this.prepareCourseStageId;
	}

	public void setPrepareCourseStageId(Integer prepareCourseStageId) {
		this.prepareCourseStageId = prepareCourseStageId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}