package cn.com.edusoa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T15:42:12.901+08:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://edusoa.com.cn/", name = "WS_PortalDataSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WSPortalDataSoap {

    @WebResult(name = "getDataListResult", targetNamespace = "http://edusoa.com.cn/")
    @RequestWrapper(localName = "getDataList", targetNamespace = "http://edusoa.com.cn/", className = "cn.com.edusoa.GetDataList")
    @WebMethod(action = "http://edusoa.com.cn/getDataList")
    @ResponseWrapper(localName = "getDataListResponse", targetNamespace = "http://edusoa.com.cn/", className = "cn.com.edusoa.GetDataListResponse")
    public cn.com.edusoa.DataListResult getDataList(
        @WebParam(name = "userId", targetNamespace = "http://edusoa.com.cn/")
        java.lang.String userId,
        @WebParam(name = "dataType", targetNamespace = "http://edusoa.com.cn/")
        java.lang.String dataType,
        @WebParam(name = "dataNum", targetNamespace = "http://edusoa.com.cn/")
        int dataNum,
        @WebParam(name = "userToken", targetNamespace = "http://edusoa.com.cn/")
        java.lang.String userToken,
        @WebParam(name = "timeStamp", targetNamespace = "http://edusoa.com.cn/")
        java.lang.String timeStamp
    );
}
