package cn.com.edusoa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T15:42:12.917+08:00
 * Generated source version: 2.7.5
 * 
                  wsdlLocation = "file:/D:/2013-05--30/a/WS_PortalData.wsdl",
 */
@WebServiceClient(name = "WS_PortalData", 
                  targetNamespace = "http://edusoa.com.cn/") 
public class WSPortalData extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://edusoa.com.cn/", "WS_PortalData");
    public final static QName WSPortalDataSoap = new QName("http://edusoa.com.cn/", "WS_PortalDataSoap");
    public final static QName WSPortalDataSoap12 = new QName("http://edusoa.com.cn/", "WS_PortalDataSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/2013-05--30/a/WS_PortalData.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSPortalData.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/2013-05--30/a/WS_PortalData.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSPortalData(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSPortalData(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSPortalData() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSPortalData(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSPortalData(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSPortalData(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WSPortalDataSoap
     */
    @WebEndpoint(name = "WS_PortalDataSoap")
    public WSPortalDataSoap getWSPortalDataSoap() {
        return super.getPort(WSPortalDataSoap, WSPortalDataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSPortalDataSoap
     */
    @WebEndpoint(name = "WS_PortalDataSoap")
    public WSPortalDataSoap getWSPortalDataSoap(WebServiceFeature... features) {
        return super.getPort(WSPortalDataSoap, WSPortalDataSoap.class, features);
    }
    /**
     *
     * @return
     *     returns WSPortalDataSoap
     */
    @WebEndpoint(name = "WS_PortalDataSoap12")
    public WSPortalDataSoap getWSPortalDataSoap12() {
        return super.getPort(WSPortalDataSoap12, WSPortalDataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSPortalDataSoap
     */
    @WebEndpoint(name = "WS_PortalDataSoap12")
    public WSPortalDataSoap getWSPortalDataSoap12(WebServiceFeature... features) {
        return super.getPort(WSPortalDataSoap12, WSPortalDataSoap.class, features);
    }

}
