
package cn.com.edusoa;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T15:42:12.917+08:00
 * Generated source version: 2.7.5
 * 
 */
 
public class WSPortalDataSoap_WSPortalDataSoap_Server{

    protected WSPortalDataSoap_WSPortalDataSoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new WSPortalDataSoapImpl1();
        String address = "http://localhost/WCFService/WS_PortalData.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new WSPortalDataSoap_WSPortalDataSoap_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
