
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cn.com.edusoa;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T15:42:12.901+08:00
 * Generated source version: 2.7.5
 * 
                      wsdlLocation = "file:/D:/2013-05--30/a/WS_PortalData.wsdl",
 */

@javax.jws.WebService(
                      serviceName = "WS_PortalData",
                      portName = "WS_PortalDataSoap12",
                      targetNamespace = "http://edusoa.com.cn/",
                      endpointInterface = "cn.com.edusoa.WSPortalDataSoap")
                      
public class WSPortalDataSoapImpl1 implements WSPortalDataSoap {

    private static final Logger LOG = Logger.getLogger(WSPortalDataSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see cn.com.edusoa.WSPortalDataSoap#getDataList(java.lang.String  userId ,)java.lang.String  dataType ,)int  dataNum ,)java.lang.String  userToken ,)java.lang.String  timeStamp )*
     */
    public cn.com.edusoa.DataListResult getDataList(java.lang.String userId,java.lang.String dataType,int dataNum,java.lang.String userToken,java.lang.String timeStamp) { 
        LOG.info("Executing operation getDataList");
        System.out.println(userId);
        System.out.println(dataType);
        System.out.println(dataNum);
        System.out.println(userToken);
        System.out.println(timeStamp);
        try {
            cn.com.edusoa.DataListResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
