<#if subjectList??>
    <table border="1">
        <tr>
            <th>学科ID</th>
            <th>学科名称</th>
            <th>工作室总数</th>
            <th>原创文章数</th>
            <th>原创文章积分</th>
            <th>转载文章数</th>
              <th>转载文章积分</th>
              <th>推荐文章数</th>
              <th>推荐文章积分</th>
              <th>资源数</th>
               <th>资源积分</th>
                <th>推荐资源数</th>
                 <th>推荐资源积分</th>
                  <th>评论数</th>
                   <th>评论积分</th>
                    <th>协作组数</th>
                     <th>集备数</th>
                      <th>活动数</th>
        </tr>
        
        <#list subjectList as sub>
            <tr>
                <td>
                    ${sub.subjectId}
                </td>
                <td>
                    ${sub.subjectName!?html}
                </td>
                <td>
                    ${sub.userCount}
                </td>
                <td>
                    ${sub.originalArticleCount}
                </td>
                <td>
                    ${sub.originalArticleScore}
                </td>
                <td>
                    ${sub.referencedArticleCount}
                </td>
                <td>
                    ${sub.referencedArticleScore}
                </td>
                <td>
                    ${sub.recommendArticleCount}
                </td>
                <td>
                    ${sub.recommendArticleScore}
                </td>
                <td>
                    ${sub.resourceCount}
                </td>
                <td>
                    ${sub.resourceScore}
                </td> 
                <td>
                    ${sub.recommendResourceCount}
                </td>
                <td>
                    ${sub.recommendResourceScore}
                </td>    
                <td>
                    ${sub.commentCount}
                </td>
                <td>
                    ${sub.commentScore}
                </td>     
                <td>
                    ${sub.groupCount}
                </td>
                <td>
                    ${sub.prepareCourseCountCount}
                </td>     
                <td>
                    ${sub.actionCount}
                </td> 
            </tr>
        </#list>
    </table>
</#if>
