package com.dsideal.ws.shareclient.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-15T09:54:20.046+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "WS_DataEX_ShareImplService", 
                  wsdlLocation = "http://localhost:8840/DataEX_share/webservice/dataEX_share?wsdl",
                  targetNamespace = "http://dataEX_share") 
public class WSDataEXShareImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dataEX_share", "WS_DataEX_ShareImplService");
    public final static QName WSDataEXShareImplPort = new QName("http://dataEX_share", "WS_DataEX_ShareImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8840/DataEX_share/webservice/dataEX_share?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSDataEXShareImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8840/DataEX_share/webservice/dataEX_share?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSDataEXShareImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSDataEXShareImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSDataEXShareImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns WSDataEXShare
     */
    @WebEndpoint(name = "WS_DataEX_ShareImplPort")
    public WSDataEXShare getWSDataEXShareImplPort() {
        return super.getPort(WSDataEXShareImplPort, WSDataEXShare.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSDataEXShare
     */
    @WebEndpoint(name = "WS_DataEX_ShareImplPort")
    public WSDataEXShare getWSDataEXShareImplPort(WebServiceFeature... features) {
        return super.getPort(WSDataEXShareImplPort, WSDataEXShare.class, features);
    }

}
