
package com.dsideal.ws.shareclient.impl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-15T09:54:19.984+08:00
 * Generated source version: 2.7.4
 * 
 */
public final class WSDataEXShare_WSDataEXShareImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://dataEX_share", "WS_DataEX_ShareImplService");

    private WSDataEXShare_WSDataEXShareImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WSDataEXShareImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WSDataEXShareImplService ss = new WSDataEXShareImplService(wsdlURL, SERVICE_NAME);
        WSDataEXShare port = ss.getWSDataEXShareImplPort();  
        
        {
        System.out.println("Invoking queryDataDiff...");
        com.dsideal.ws.shareclient.impl.DataEXQueryRequest _queryDataDiff_queryRequest = null;
        com.dsideal.ws.shareclient.impl.DataEXQueryResult _queryDataDiff__return = port.queryDataDiff(_queryDataDiff_queryRequest);
        System.out.println("queryDataDiff.result=" + _queryDataDiff__return);


        }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_userName = "";
        java.lang.String _login_password = "";
        java.lang.String _login_loginTime = "";
        java.lang.String _login__return = port.login(_login_userName, _login_password, _login_loginTime);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking queryDataNO...");
        com.dsideal.ws.shareclient.impl.DataEXQueryRequest _queryDataNO_queryRequest = null;
        com.dsideal.ws.shareclient.impl.DataEXPageResult _queryDataNO__return = port.queryDataNO(_queryDataNO_queryRequest);
        System.out.println("queryDataNO.result=" + _queryDataNO__return);


        }
        {
        System.out.println("Invoking queryData...");
        com.dsideal.ws.shareclient.impl.DataEXQueryRequest _queryData_queryRequest = null;
        int _queryData_arg1 = 0;
        com.dsideal.ws.shareclient.impl.DataEXQueryResult _queryData__return = port.queryData(_queryData_queryRequest, _queryData_arg1);
        System.out.println("queryData.result=" + _queryData__return);


        }
        {
        System.out.println("Invoking queryDataConfirm...");
        com.dsideal.ws.shareclient.impl.DataEXConfirmRequest _queryDataConfirm_queryRequest = null;
        java.util.List<java.lang.String> _queryDataConfirm_arg1 = null;
        port.queryDataConfirm(_queryDataConfirm_queryRequest, _queryDataConfirm_arg1);


        }

        System.exit(0);
    }

}
